import { execFileSync } from "child_process";
import { createRequire } from "module";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Run the esbuild binary directly (stdio inherited) instead of the JS API:
// the JS API spawns its native service process with piped stdio, which some
// sandboxed environments block with EPERM. Options and output are identical
// to the previous `esbuild.context()` setup.
const require = createRequire(import.meta.url);
const esbuildBin = require.resolve("esbuild/bin/esbuild");

const args = [
  "src/main.ts",
  "--bundle",
  ...[
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collapse",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ].map((m) => `--external:${m}`),
  "--format=cjs",
  "--target=es2018",
  "--log-level=info",
  "--tree-shaking=true",
  `--banner:js=${banner}`,
  "--outfile=main.js",
];
if (!prod) args.push("--sourcemap=inline", "--watch");

execFileSync(process.execPath, [esbuildBin, ...args], { stdio: "inherit" });
