/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageHeaderBookmarksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ICON_BOOKMARK = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/></svg>`;
var ICON_FOLDER = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg>`;
var ICON_FILE = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></svg>`;
var ICON_SEARCH = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>`;
var ICON_CHEVRON = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>`;
var ICON_CLOSE = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>`;
var PageHeaderBookmarksPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.observer = null;
    this.syncQueued = false;
    this.backdrop = null;
    this.popover = null;
    this.anchor = null;
    this.listEl = null;
    this.expanded = /* @__PURE__ */ new Set();
    this.keyHandler = (e) => {
      if (e.key === "Escape") this.closePopover();
    };
    this.resizeHandler = () => {
      if (this.anchor && this.anchor.isConnected) this.positionPopover();
      else this.closePopover();
    };
  }
  async onload() {
    this.app.workspace.onLayoutReady(() => this.syncHeaders());
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.syncHeaders();
        if (this.popover && this.anchor && !this.anchor.isConnected) this.closePopover();
      })
    );
    this.observer = new MutationObserver(() => this.queueSync());
    this.observer.observe(this.app.workspace.containerEl, { childList: true, subtree: true });
    this.register(() => {
      var _a;
      (_a = this.observer) == null ? void 0 : _a.disconnect();
      this.closePopover();
      this.app.workspace.containerEl.querySelectorAll(".phb-button").forEach((btn) => btn.remove());
    });
  }
  /* ------------------------------------------------------------------ */
  /* Page header button ("page header" as defined by the Commander      */
  /* plugin: the title bar at the top of each pane, i.e. .view-header)  */
  /* ------------------------------------------------------------------ */
  queueSync() {
    if (this.syncQueued) return;
    this.syncQueued = true;
    requestAnimationFrame(() => {
      this.syncQueued = false;
      this.syncHeaders();
    });
  }
  syncHeaders() {
    const root = this.app.workspace.containerEl;
    root.querySelectorAll(".view-header").forEach((header) => {
      if (header.querySelector(".phb-button")) return;
      const btn = header.createEl("button", {
        cls: "phb-button clickable-icon view-action",
        attr: { "aria-label": "\u4E66\u7B7E" }
      });
      btn.innerHTML = ICON_BOOKMARK;
      const right = header.querySelector(".view-header-right");
      const actions = header.querySelector(".view-actions");
      if (right && actions) right.insertBefore(btn, actions);
      else if (right) right.appendChild(btn);
      else header.appendChild(btn);
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.togglePopover(btn);
      });
    });
  }
  /* ------------------------------------------------------------------ */
  /* Popover lifecycle                                                   */
  /* ------------------------------------------------------------------ */
  togglePopover(btn) {
    if (this.popover && this.anchor === btn) this.closePopover();
    else this.openPopover(btn);
  }
  openPopover(btn) {
    this.closePopover();
    this.anchor = btn;
    const backdrop = createDiv({ cls: "phb-backdrop" });
    const popover = createDiv({ cls: "phb-popover" });
    document.body.appendChild(backdrop);
    document.body.appendChild(popover);
    this.backdrop = backdrop;
    this.popover = popover;
    const header = popover.createDiv({ cls: "phb-popover-header" });
    header.createSpan({ cls: "phb-popover-title", text: "\u4E66\u7B7E" });
    const closeBtn = header.createEl("button", {
      cls: "phb-close clickable-icon",
      attr: { "aria-label": "\u5173\u95ED" }
    });
    closeBtn.innerHTML = ICON_CLOSE;
    closeBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.closePopover();
    });
    this.listEl = popover.createDiv({ cls: "phb-popover-list" });
    this.expanded.clear();
    this.renderInto(this.listEl);
    backdrop.addEventListener("click", () => this.closePopover());
    window.addEventListener("keydown", this.keyHandler);
    window.addEventListener("resize", this.resizeHandler);
    this.positionPopover();
  }
  closePopover() {
    var _a, _b;
    (_a = this.backdrop) == null ? void 0 : _a.remove();
    (_b = this.popover) == null ? void 0 : _b.remove();
    this.backdrop = null;
    this.popover = null;
    this.anchor = null;
    this.listEl = null;
    this.expanded.clear();
    window.removeEventListener("keydown", this.keyHandler);
    window.removeEventListener("resize", this.resizeHandler);
  }
  positionPopover() {
    if (!this.popover || !this.anchor) return;
    const popover = this.popover;
    popover.style.visibility = "hidden";
    const rect = this.anchor.getBoundingClientRect();
    const pw = popover.offsetWidth;
    const ph = popover.offsetHeight;
    let left = rect.left;
    let top = rect.bottom + 6;
    if (left + pw > window.innerWidth - 8) left = Math.max(8, window.innerWidth - pw - 8);
    if (top + ph > window.innerHeight - 8) top = Math.max(8, rect.top - ph - 6);
    popover.style.left = `${left}px`;
    popover.style.top = `${top}px`;
    popover.style.visibility = "visible";
  }
  /* ------------------------------------------------------------------ */
  /* Rendering                                                           */
  /* ------------------------------------------------------------------ */
  renderInto(list) {
    var _a, _b;
    list.empty();
    const bookmarksInternal = (_b = (_a = this.app.internalPlugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.bookmarks;
    if (!(bookmarksInternal == null ? void 0 : bookmarksInternal.enabled)) {
      list.createDiv({ cls: "phb-empty", text: "\u6838\u5FC3\u63D2\u4EF6\u300C\u4E66\u7B7E\u300D\u672A\u542F\u7528" });
      const enableBtn = list.createEl("button", { cls: "phb-enable", text: "\u542F\u7528\u4E66\u7B7E\u63D2\u4EF6" });
      enableBtn.addEventListener("click", () => {
        var _a2;
        void ((_a2 = bookmarksInternal == null ? void 0 : bookmarksInternal.enable) == null ? void 0 : _a2.call(bookmarksInternal));
        window.setTimeout(() => {
          this.renderInto(list);
          this.positionPopover();
        }, 150);
      });
      return;
    }
    const nodes = this.buildTree();
    if (nodes.length === 0) {
      list.createDiv({
        cls: "phb-empty",
        text: "\u6682\u65E0\u4E66\u7B7E\u3002\u5728\u6587\u4EF6\u6216\u6587\u4EF6\u5939\u7684\u53F3\u952E\u83DC\u5355\u4E2D\u70B9\u51FB\u300C\u6DFB\u52A0\u4E66\u7B7E\u300D\u3002"
      });
      return;
    }
    this.renderNodes(list, nodes);
  }
  buildTree() {
    var _a;
    const bm = this.app.bookmarks;
    const root = [];
    if (!bm) return root;
    const items = Array.isArray(bm.items) ? bm.items : [];
    const groups = Array.isArray(bm.groups) ? bm.groups : [];
    for (const it of items) {
      if ((it == null ? void 0 : it.type) === "group" && Array.isArray(it.items) && it.items.length > 0) {
        const kids = it.items.map((x) => this.itemToNode(x)).filter((n) => n !== null);
        if (kids.length > 0) root.push({ kind: "group", title: it.title || "\u672A\u547D\u540D\u5206\u7EC4", children: kids });
      } else {
        const n = this.itemToNode(it);
        if (n) root.push(n);
      }
    }
    for (const g of groups) {
      const kids = ((_a = g == null ? void 0 : g.items) != null ? _a : []).map((x) => this.itemToNode(x)).filter((n) => n !== null);
      if (kids.length > 0) root.push({ kind: "group", id: g == null ? void 0 : g.id, title: (g == null ? void 0 : g.title) || "\u672A\u547D\u540D\u5206\u7EC4", children: kids });
    }
    return root;
  }
  itemToNode(it) {
    var _a, _b, _c, _d, _e, _f;
    if (!it) return null;
    const type = it.type;
    if (type === "file") {
      const path = (_a = it.path) != null ? _a : "";
      const file = this.app.vault.getAbstractFileByPath(path);
      const missing = !(file instanceof import_obsidian.TFile);
      return { kind: "file", title: it.title || path.replace(/\.md$/, ""), path, subpath: it.subpath, missing };
    }
    if (type === "folder") {
      return { kind: "folder", title: it.title || ((_b = it.path) != null ? _b : "").split("/").pop() || "", path: (_c = it.path) != null ? _c : "" };
    }
    if (type === "search") {
      const query = (_e = (_d = it.query) != null ? _d : it.path) != null ? _e : "";
      return { kind: "search", title: it.title || query || "\u641C\u7D22", query, path: (_f = it.path) != null ? _f : "" };
    }
    return null;
  }
  /** Stable identity for a tree node, used to keep expansion state across re-renders. */
  nodeKey(node) {
    var _a, _b, _c, _d, _e, _f;
    switch (node.kind) {
      case "file":
        return `file:${(_a = node.path) != null ? _a : ""}`;
      case "folder":
        return `folder:${(_b = node.path) != null ? _b : ""}`;
      case "search":
        return `search:${(_e = (_d = (_c = node.query) != null ? _c : node.path) != null ? _d : node.title) != null ? _e : ""}`;
      case "group":
        return `group:${(_f = node.id) != null ? _f : node.title}`;
      default:
        return "";
    }
  }
  renderNodes(container, nodes) {
    for (const node of nodes) container.appendChild(this.renderNode(node));
  }
  renderNode(node) {
    const wrap = createDiv({ cls: "phb-node" });
    const row = wrap.createDiv({ cls: ["phb-item", `phb-item-${node.kind}`] });
    if (node.kind === "group" || node.kind === "folder") {
      const isOpen = this.expanded.has(this.nodeKey(node));
      const caret = row.createSpan({ cls: ["phb-caret", ...isOpen ? ["phb-open"] : []] });
      caret.innerHTML = ICON_CHEVRON;
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_FOLDER;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        this.toggleNode(node);
      });
      if (isOpen) {
        const children = createDiv({ cls: "phb-children" });
        wrap.appendChild(children);
        this.renderNodes(children, this.childrenOf(node));
      }
    } else if (node.kind === "file") {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_FILE;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      if (node.missing) row.addClass("phb-item-missing");
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        this.openFile(node);
      });
    } else {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_SEARCH;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.openSearch(node);
      });
    }
    return wrap;
  }
  /** Children of a group (its bookmarks) or a folder (vault contents, lazily). */
  childrenOf(node) {
    var _a;
    if (node.kind === "group") return (_a = node.children) != null ? _a : [];
    if (node.kind === "folder") {
      if (!node.children) {
        const folder = node.path ? this.app.vault.getAbstractFileByPath(node.path) : null;
        const kids = [];
        if (folder instanceof import_obsidian.TFolder) {
          for (const child of folder.children) {
            if (child instanceof import_obsidian.TFile) {
              kids.push({ kind: "file", title: child.basename, path: child.path });
            } else if (child instanceof import_obsidian.TFolder) {
              kids.push({ kind: "folder", title: child.name, path: child.path });
            }
          }
          kids.sort((a, b) => {
            if (a.kind === "folder" && b.kind !== "folder") return -1;
            if (a.kind !== "folder" && b.kind === "folder") return 1;
            return a.title.localeCompare(b.title, void 0, { numeric: true, sensitivity: "base" });
          });
        }
        node.children = kids;
      }
      return node.children;
    }
    return [];
  }
  toggleNode(node) {
    const key = this.nodeKey(node);
    if (this.expanded.has(key)) this.expanded.delete(key);
    else this.expanded.add(key);
    this.rerenderList();
  }
  rerenderList() {
    if (!this.listEl) return;
    const scrollTop = this.listEl.scrollTop;
    this.renderInto(this.listEl);
    this.listEl.scrollTop = scrollTop;
    this.positionPopover();
  }
  /* ------------------------------------------------------------------ */
  /* Actions                                                             */
  /* ------------------------------------------------------------------ */
  openFile(node) {
    var _a;
    if (node.missing) return;
    const linktext = ((_a = node.path) != null ? _a : "") + (node.subpath ? "#" + node.subpath : "");
    void this.app.workspace.openLinkText(linktext, "", true);
    this.closePopover();
  }
  async openSearch(node) {
    var _a, _b, _c, _d;
    try {
      const query = (_c = (_b = (_a = node.query) != null ? _a : node.path) != null ? _b : node.title) != null ? _c : "";
      const existing = this.app.workspace.getLeavesOfType("search");
      const leaf = (_d = existing[0]) != null ? _d : this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: "search", state: { query } });
        this.app.workspace.revealLeaf(leaf);
      }
    } catch (e) {
      console.error("Page Header Bookmarks: failed to open search", e);
    } finally {
      this.closePopover();
    }
  }
};
