/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageHeaderBookmarksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function normalizePath(p) {
  return p.replace(/^\/+|\/+$/g, "");
}
var ICON_FOLDER = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg>`;
var ICON_FILE = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></svg>`;
var ICON_SEARCH = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>`;
var ICON_LINK = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>`;
var ICON_GRAPH = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/></svg>`;
var ICON_CHEVRON = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>`;
var ICON_CLOSE = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>`;
var PageHeaderBookmarksPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /** Injected page-header buttons, keyed by the view they belong to. */
    this.buttons = /* @__PURE__ */ new WeakMap();
    this.backdrop = null;
    this.popover = null;
    this.anchor = null;
    this.listEl = null;
    this.expanded = /* @__PURE__ */ new Set();
    this.keyHandler = (e) => {
      if (e.key === "Escape") this.closePopover();
    };
    this.resizeHandler = () => {
      if (this.anchor && this.anchor.isConnected) this.positionPopover();
      else this.closePopover();
    };
  }
  async onload() {
    this.app.workspace.onLayoutReady(
      () => window.setTimeout(() => this.addButtonsToAllLeaves(), 100)
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.addButtonsToAllLeaves();
        if (this.popover && this.anchor && !this.anchor.isConnected) this.closePopover();
      })
    );
    this.register(() => {
      this.closePopover();
      this.removeButtonsFromAllLeaves();
    });
  }
  /* ------------------------------------------------------------------ */
  /* Page header button — same mechanism as the Commander plugin:        */
  /* ItemView.addAction() (native icon rendering + native button shape), */
  /* ordered left of the "more options" button via CSS `order`.          */
  /* ------------------------------------------------------------------ */
  addButtonsToAllLeaves() {
    window.requestAnimationFrame(
      () => this.app.workspace.iterateAllLeaves((leaf) => this.addButtonToLeaf(leaf))
    );
  }
  addButtonToLeaf(leaf) {
    const view = leaf.view;
    if (!(view instanceof import_obsidian.ItemView)) return;
    if (this.buttons.has(view)) return;
    const button = view.addAction("bookmark", "\u4E66\u7B7E", () => {
      this.togglePopover(button);
    });
    button.addClass("phb-button");
    this.buttons.set(view, button);
  }
  removeButtonsFromAllLeaves() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      if (!(view instanceof import_obsidian.ItemView)) return;
      const button = this.buttons.get(view);
      if (button) {
        button.detach();
        this.buttons.delete(view);
      }
    });
  }
  /* ------------------------------------------------------------------ */
  /* Popover lifecycle                                                   */
  /* ------------------------------------------------------------------ */
  togglePopover(btn) {
    if (this.popover && this.anchor === btn) this.closePopover();
    else this.openPopover(btn);
  }
  openPopover(btn) {
    this.closePopover();
    this.anchor = btn;
    const backdrop = createDiv({ cls: "phb-backdrop" });
    const popover = createDiv({ cls: "phb-popover" });
    document.body.appendChild(backdrop);
    document.body.appendChild(popover);
    this.backdrop = backdrop;
    this.popover = popover;
    const header = popover.createDiv({ cls: "phb-popover-header" });
    header.createSpan({ cls: "phb-popover-title", text: "\u4E66\u7B7E" });
    const closeBtn = header.createEl("button", {
      cls: "phb-close clickable-icon",
      attr: { "aria-label": "\u5173\u95ED" }
    });
    closeBtn.innerHTML = ICON_CLOSE;
    closeBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.closePopover();
    });
    this.listEl = popover.createDiv({ cls: "phb-popover-list" });
    this.expanded.clear();
    void this.renderInto(this.listEl).finally(() => this.positionPopover());
    backdrop.addEventListener("click", () => this.closePopover());
    window.addEventListener("keydown", this.keyHandler);
    window.addEventListener("resize", this.resizeHandler);
    this.positionPopover();
  }
  closePopover() {
    var _a, _b;
    (_a = this.backdrop) == null ? void 0 : _a.remove();
    (_b = this.popover) == null ? void 0 : _b.remove();
    this.backdrop = null;
    this.popover = null;
    this.anchor = null;
    this.listEl = null;
    this.expanded.clear();
    window.removeEventListener("keydown", this.keyHandler);
    window.removeEventListener("resize", this.resizeHandler);
  }
  positionPopover() {
    if (!this.popover || !this.anchor) return;
    const popover = this.popover;
    popover.style.visibility = "hidden";
    const rect = this.anchor.getBoundingClientRect();
    const pw = popover.offsetWidth;
    const ph = popover.offsetHeight;
    let left = rect.left;
    let top = rect.bottom + 6;
    if (left + pw > window.innerWidth - 8) left = Math.max(8, window.innerWidth - pw - 8);
    if (top + ph > window.innerHeight - 8) top = Math.max(8, rect.top - ph - 6);
    popover.style.left = `${left}px`;
    popover.style.top = `${top}px`;
    popover.style.visibility = "visible";
  }
  /* ------------------------------------------------------------------ */
  /* Data resolution                                                     */
  /* ------------------------------------------------------------------ */
  /**
   * Fetch bookmark data from every source we know about, newest first:
   *   1. live instances (`app.bookmarks`, `app.internalPlugins…instance`)
   *      — items may be ungrouped (old shape) or a unified list that also
   *      contains `type: "group"` entries with nested items (new shape);
   *   2. `getBookmarks()` flat list when the instance exposes it;
   *   3. the core plugin's data file `.obsidian/bookmarks.json` (most
   *      reliable across versions; read on demand so it is always fresh).
   */
  async resolveBookmarks() {
    var _a, _b, _c;
    const liveSources = [];
    try {
      liveSources.push(this.app.bookmarks);
    } catch (e) {
    }
    try {
      liveSources.push(
        (_c = (_b = (_a = this.app.internalPlugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.bookmarks) == null ? void 0 : _c.instance
      );
    } catch (e) {
    }
    for (const source of liveSources) {
      if (!source) continue;
      try {
        const s = source;
        const items = Array.isArray(s.items) ? s.items : [];
        const groups = Array.isArray(s.groups) ? s.groups : [];
        if (items.length > 0 || groups.length > 0) return { items, groups };
        if (typeof s.getBookmarks === "function") {
          const flat = s.getBookmarks();
          if (Array.isArray(flat) && flat.length > 0) return { items: flat, groups: [] };
        }
      } catch (e) {
      }
    }
    try {
      const adapter = this.app.vault.adapter;
      if (adapter && typeof adapter.read === "function") {
        const raw = await adapter.read(".obsidian/bookmarks.json");
        if (raw) {
          const data = JSON.parse(raw);
          return {
            items: Array.isArray(data == null ? void 0 : data.items) ? data.items : [],
            groups: Array.isArray(data == null ? void 0 : data.groups) ? data.groups : []
          };
        }
      }
    } catch (e) {
    }
    return null;
  }
  /* ------------------------------------------------------------------ */
  /* Rendering                                                           */
  /* ------------------------------------------------------------------ */
  async renderInto(list) {
    list.empty();
    const data = await this.resolveBookmarks();
    console.debug(
      "Page Header Bookmarks: bookmark data resolved",
      data ? { items: data.items.length, groups: data.groups.length } : null
    );
    if (!data) {
      list.createDiv({
        cls: "phb-empty",
        text: "\u672A\u8BFB\u53D6\u5230\u4E66\u7B7E\u6570\u636E\uFF08\u8BF7\u786E\u8BA4\u6838\u5FC3\u63D2\u4EF6\u300C\u4E66\u7B7E\u300D\u5DF2\u542F\u7528\uFF09"
      });
      const enableBtn = list.createEl("button", { cls: "phb-enable", text: "\u542F\u7528\u4E66\u7B7E\u63D2\u4EF6" });
      enableBtn.addEventListener("click", () => {
        var _a, _b, _c, _d;
        void ((_d = (_c = (_b = (_a = this.app.internalPlugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.bookmarks) == null ? void 0 : _c.enable) == null ? void 0 : _d.call(_c));
        window.setTimeout(() => {
          void this.renderInto(list).then(() => this.positionPopover());
        }, 200);
      });
      return;
    }
    const nodes = this.buildTree(data);
    if (nodes.length === 0) {
      list.createDiv({
        cls: "phb-empty",
        text: "\u6682\u65E0\u4E66\u7B7E\u3002\u5728\u6587\u4EF6\u6216\u6587\u4EF6\u5939\u7684\u53F3\u952E\u83DC\u5355\u4E2D\u70B9\u51FB\u300C\u6DFB\u52A0\u4E66\u7B7E\u300D\u3002"
      });
      return;
    }
    this.renderNodes(list, nodes);
  }
  buildTree(data) {
    var _a;
    const covered = this.computeCoveredPaths(data);
    const convert = (it) => {
      if (!it) return null;
      if ((it.type === "file" || it.type === "folder") && it.path && covered.has(normalizePath(it.path))) {
        return null;
      }
      return this.itemToNode(it);
    };
    const root = [];
    for (const it of data.items) {
      if ((it == null ? void 0 : it.type) === "group") {
        const kids = (Array.isArray(it.items) ? it.items : []).map(convert).filter((n) => n !== null);
        root.push({ kind: "group", title: it.title || "\u672A\u547D\u540D\u5206\u7EC4", children: kids });
      } else {
        const n = convert(it);
        if (n) root.push(n);
      }
    }
    for (const g of data.groups) {
      const kids = ((_a = g == null ? void 0 : g.items) != null ? _a : []).map(convert).filter((n) => n !== null);
      root.push({ kind: "group", id: g == null ? void 0 : g.id, title: (g == null ? void 0 : g.title) || "\u672A\u547D\u540D\u5206\u7EC4", children: kids });
    }
    this.dropRootDuplicatesOfGroupItems(root);
    console.debug("Page Header Bookmarks: tree built", {
      items: data.items.length,
      groups: data.groups.length,
      coveredByFolders: covered.size,
      nodes: root.length
    });
    return root;
  }
  /**
   * Paths that should not appear as standalone bookmarks: every file and
   * folder inside any bookmarked folder (they are reachable by expanding
   * the folder bookmark instead).
   */
  computeCoveredPaths(data) {
    var _a;
    const folderPaths = /* @__PURE__ */ new Set();
    const collect = (it) => {
      var _a2;
      if (!it) return;
      if (it.type === "folder" && it.path) folderPaths.add(normalizePath(it.path));
      ((_a2 = it.items) != null ? _a2 : []).forEach(collect);
    };
    data.items.forEach(collect);
    for (const g of data.groups) ((_a = g == null ? void 0 : g.items) != null ? _a : []).forEach(collect);
    const covered = /* @__PURE__ */ new Set();
    const visit = (path) => {
      const folder = this.app.vault.getAbstractFileByPath(path);
      if (!(folder instanceof import_obsidian.TFolder)) return;
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFile) {
          covered.add(child.path);
        } else if (child instanceof import_obsidian.TFolder) {
          covered.add(child.path);
          visit(child.path);
        }
      }
    };
    for (const p of folderPaths) visit(p);
    return covered;
  }
  itemToNode(it) {
    var _a, _b, _c, _d, _e, _f;
    if (!it) return null;
    const type = it.type;
    if (type === "file") {
      const path = normalizePath((_a = it.path) != null ? _a : "");
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile)) return null;
      const title = it.title && it.title.trim() ? it.title : file.basename;
      return { kind: "file", title, path, subpath: it.subpath };
    }
    if (type === "folder") {
      const path = normalizePath((_b = it.path) != null ? _b : "");
      const folder = this.app.vault.getAbstractFileByPath(path);
      if (!(folder instanceof import_obsidian.TFolder)) return null;
      const title = it.title && it.title.trim() ? it.title : folder.name;
      return { kind: "folder", title, path };
    }
    if (type === "search") {
      const query = (_d = (_c = it.query) != null ? _c : it.path) != null ? _d : "";
      return { kind: "search", title: it.title || query || "\u641C\u7D22", query, path: (_e = it.path) != null ? _e : "" };
    }
    if (type === "url") {
      return { kind: "url", title: it.title || it.url || "\u94FE\u63A5", url: (_f = it.url) != null ? _f : "" };
    }
    if (type === "graph") {
      return { kind: "graph", title: it.title || "\u56FE\u8C31", options: it.options };
    }
    return null;
  }
  /** Stable identity for a tree node, used to keep expansion state across re-renders. */
  nodeKey(node) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    switch (node.kind) {
      case "file":
        return `file:${(_a = node.path) != null ? _a : ""}`;
      case "folder":
        return `folder:${(_b = node.path) != null ? _b : ""}`;
      case "search":
        return `search:${(_e = (_d = (_c = node.query) != null ? _c : node.path) != null ? _d : node.title) != null ? _e : ""}`;
      case "url":
        return `url:${(_g = (_f = node.url) != null ? _f : node.title) != null ? _g : ""}`;
      case "graph":
        return `graph:${(_h = node.title) != null ? _h : ""}`;
      case "group":
        return `group:${(_i = node.id) != null ? _i : node.title}`;
      default:
        return "";
    }
  }
  /** Exact bookmark target key (type + target fields) for duplicate detection. */
  targetKey(n) {
    var _a, _b, _c, _d, _e, _f, _g;
    switch (n.kind) {
      case "file":
        return `file:${(_a = n.path) != null ? _a : ""}#${(_b = n.subpath) != null ? _b : ""}`;
      case "folder":
        return `folder:${(_c = n.path) != null ? _c : ""}`;
      case "search":
        return `search:${(_e = (_d = n.query) != null ? _d : n.path) != null ? _e : ""}`;
      case "url":
        return `url:${(_f = n.url) != null ? _f : ""}`;
      case "graph":
        return `graph:${(_g = n.title) != null ? _g : ""}`;
      default:
        return "";
    }
  }
  /**
   * Real bookmark data can contain the same target both inside a group and
   * as a standalone top-level item (e.g. a folder that is represented by a
   * group bookmark). The standalone copy is a duplicate of something already
   * visible when the group is expanded, so drop it. Matching is by exact
   * target key only — never by basename or path prefix — to avoid hiding
   * legitimately separate bookmarks (e.g. same-named files elsewhere).
   */
  dropRootDuplicatesOfGroupItems(root) {
    const inGroups = /* @__PURE__ */ new Set();
    const collectChildren = (nodes) => {
      var _a;
      for (const n of nodes) {
        if (n.kind === "group") collectChildren((_a = n.children) != null ? _a : []);
        else inGroups.add(this.targetKey(n));
      }
    };
    const collectGroups = (nodes) => {
      var _a, _b;
      for (const n of nodes) {
        if (n.kind === "group") {
          collectChildren((_a = n.children) != null ? _a : []);
          collectGroups((_b = n.children) != null ? _b : []);
        }
      }
    };
    collectGroups(root);
    for (let i = root.length - 1; i >= 0; i--) {
      const n = root[i];
      if (n.kind !== "group" && inGroups.has(this.targetKey(n))) root.splice(i, 1);
    }
  }
  renderNodes(container, nodes) {
    for (const node of nodes) container.appendChild(this.renderNode(node));
  }
  renderNode(node) {
    var _a, _b;
    const wrap = createDiv({ cls: "phb-node" });
    const row = wrap.createDiv({ cls: ["phb-item", `phb-item-${node.kind}`] });
    if (node.kind === "group" || node.kind === "folder") {
      const hasChildren = node.kind === "folder" || ((_b = (_a = node.children) == null ? void 0 : _a.length) != null ? _b : 0) > 0;
      const isOpen = this.expanded.has(this.nodeKey(node));
      const caret = row.createSpan({ cls: ["phb-caret", ...isOpen ? ["phb-open"] : []] });
      caret.innerHTML = ICON_CHEVRON;
      if (!hasChildren) caret.addClass("phb-caret-empty");
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_FOLDER;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        if (hasChildren) this.toggleNode(node);
      });
      if (isOpen) {
        const children = createDiv({ cls: "phb-children" });
        wrap.appendChild(children);
        this.renderNodes(children, this.childrenOf(node));
      }
    } else if (node.kind === "file") {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_FILE;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        this.openFile(node);
      });
    } else if (node.kind === "search") {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_SEARCH;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.openSearch(node);
      });
    } else if (node.kind === "url") {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_LINK;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        this.openUrl(node);
      });
    } else {
      const icon = row.createSpan({ cls: "phb-item-icon" });
      icon.innerHTML = ICON_GRAPH;
      row.createDiv({ cls: "phb-item-title", text: node.title });
      row.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.openGraph(node);
      });
    }
    return wrap;
  }
  /** Children of a group (its bookmarks) or a folder (vault contents, lazily). */
  childrenOf(node) {
    var _a;
    if (node.kind === "group") return (_a = node.children) != null ? _a : [];
    if (node.kind === "folder") {
      if (!node.children) {
        const folder = node.path ? this.app.vault.getAbstractFileByPath(node.path) : null;
        const kids = [];
        if (folder instanceof import_obsidian.TFolder) {
          for (const child of folder.children) {
            if (child instanceof import_obsidian.TFile) {
              kids.push({ kind: "file", title: child.basename, path: child.path });
            } else if (child instanceof import_obsidian.TFolder) {
              kids.push({ kind: "folder", title: child.name, path: child.path });
            }
          }
          kids.sort((a, b) => {
            if (a.kind === "folder" && b.kind !== "folder") return -1;
            if (a.kind !== "folder" && b.kind === "folder") return 1;
            return a.title.localeCompare(b.title, void 0, { numeric: true, sensitivity: "base" });
          });
        }
        node.children = kids;
      }
      return node.children;
    }
    return [];
  }
  toggleNode(node) {
    var _a, _b;
    if (node.kind === "group" && ((_b = (_a = node.children) == null ? void 0 : _a.length) != null ? _b : 0) === 0) return;
    const key = this.nodeKey(node);
    if (this.expanded.has(key)) this.expanded.delete(key);
    else this.expanded.add(key);
    this.rerenderList();
  }
  rerenderList() {
    if (!this.listEl) return;
    const scrollTop = this.listEl.scrollTop;
    void this.renderInto(this.listEl).then(() => {
      if (this.listEl) this.listEl.scrollTop = scrollTop;
      this.positionPopover();
    });
  }
  /* ------------------------------------------------------------------ */
  /* Actions                                                             */
  /* ------------------------------------------------------------------ */
  openFile(node) {
    var _a;
    const file = node.path ? this.app.vault.getAbstractFileByPath(node.path) : null;
    if (!(file instanceof import_obsidian.TFile)) {
      this.closePopover();
      return;
    }
    const linktext = ((_a = node.path) != null ? _a : "") + (node.subpath ? "#" + node.subpath : "");
    void this.app.workspace.openLinkText(linktext, "", true);
    this.closePopover();
  }
  async openSearch(node) {
    var _a, _b, _c, _d;
    try {
      const query = (_c = (_b = (_a = node.query) != null ? _a : node.path) != null ? _b : node.title) != null ? _c : "";
      const existing = this.app.workspace.getLeavesOfType("search");
      const leaf = (_d = existing[0]) != null ? _d : this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: "search", state: { query } });
        this.app.workspace.revealLeaf(leaf);
      }
    } catch (e) {
      console.error("Page Header Bookmarks: failed to open search", e);
    } finally {
      this.closePopover();
    }
  }
  openUrl(node) {
    var _a;
    const url = (_a = node.url) != null ? _a : "";
    if (url) {
      try {
        window.open(url, "_blank");
      } catch (e) {
        console.error("Page Header Bookmarks: failed to open url", e);
      }
    }
    this.closePopover();
  }
  async openGraph(node) {
    var _a;
    try {
      const existing = this.app.workspace.getLeavesOfType("graph");
      const leaf = (_a = existing[0]) != null ? _a : this.app.workspace.getRightLeaf(false);
      if (leaf) {
        const state = { query: "" };
        if (node.options && typeof node.options === "object") Object.assign(state, node.options);
        await leaf.setViewState({ type: "graph", state });
        this.app.workspace.revealLeaf(leaf);
      }
    } catch (e) {
      console.error("Page Header Bookmarks: failed to open graph", e);
    } finally {
      this.closePopover();
    }
  }
};
